---
# handlers file for ansible-pritunl
- name: restart mongod
  listen: pritunl installed
  service:
    name: mongod
    enabled: yes
    state: restarted
  become: yes

- name: restart pritunl
  listen: pritunl installed
  service:
    name: pritunl
    enabled: yes
    state: restarted
  become: yes
